version: '2'
services:
  users_db:
    image: mysql:5.7
    ports:
      - "5434:5434"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: users
      MYSQL_HOST: users_db
  users_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails s -p 3309 -b '0.0.0.0'"
    ports:
      - "3009:3009"
    depends_on:
      - users_db